name: build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20, 22, 24]

    steps:
      - uses: actions/checkout@v6

      - uses: depot/setup-action@v1

      - name: Build NodeJS Community Docker image
        uses: depot/build-push-action@v1
        with:
          push: false
          context: .
          file: Dockerfile
          build-args: AGENT_VERSION=ci-build