name: build

on:
  pull_request:
    branches:
      - main

jobs:

  build-agent-image:
    runs-on: depot-ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: depot/setup-action@v1

      - name: Build NodeJS Community Docker image
        uses: depot/build-push-action@v1
        with:
          push: false
          context: .
          file: Dockerfile
          build-args: AGENT_VERSION=ci-build

  build:
    runs-on: depot-ubuntu-24.04
    strategy:
      matrix:
        node-version: [18, 20, 22, 24]

    steps:
      - uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn compile
